### ISSUE TITLE
Doesn't Work.

### ISSUE THREAD

**Issue by xGioChR** [HYPExMon5ter/PlayerMention#1]
Hello.
I am using the latest version of PlayerMention, PaperSpigot and DeluxeChat.
Whenever i try to mention anyone, The plugin just doesn't work.

**Comment by HYPExMon5ter** [comment]
This doesn’t really help me, is there errors? Show me your config, how did you try to mention someone? Etc.

**Comment by HYPExMon5ter** [comment]
No reply, closing.
