### ISSUE TITLE
Asynchronous Updater

### ISSUE THREAD

**Issue by TuxCoding** [HYPExMon5ter/PlayerMention#2]
You're checking for plugin updates on every admin join on the main Thread. This is not good practice, because first you are checking it for **every** admin join, so you should definitely add delay so it updates only 24 hours or so.

Furthermore you should not do network requests on the main thread. Those requests are blocking. It means that the main thread cannot calculate any further until it gets the response. Since Minecraft uses most of the time only the main Thread, it can have some impact on the server load.

**Comment by HYPExMon5ter** [comment]
Good point, I’ll see what I can do, or you can make a pull request of said features if you know how to implement them

**Comment by HYPExMon5ter** [comment]
Made the Updater Async, thanks for your suggestion.
